
apiVersion: v1
kind: Namespace
metadata:
  name: front-end
---

apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: front-end
  labels:
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: "http"
    targetPort: 8080
  selector:
    app: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-deployment
  namespace: front-end
  labels:
    app: web
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        octopusexport: OctopusExport
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname